resources:
- api-service.yaml
- manager.yaml

# the following config is for teaching kustomize how to do var substitution
vars:
- name: API_SERVICE_NAMESPACE # namespace of the service
  objref:
    kind: Service
    version: v1
    name: api-service
  fieldref:
    fieldpath: metadata.namespace
- name: API_SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: api-service
- name: MANAGER_CONTAINER_IMAGE
  objref:
    group: apps
    kind: Deployment
    version: v1
    name: controller-manager
  fieldref:
    fieldpath: spec.template.spec.containers.[name=manager].image
